# Generated by Django 2.2.24 on 2022-04-13 15:28

from django.db import migrations
import phonenumbers


def resolve_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        flat.owners_pure_phone = (
            phonenumber
            if phonenumbers.is_valid_number_for_region(phonenumber, 'RU')
            else None
        )
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20220413_1926'),
    ]

    operations = [
        migrations.RunPython(resolve_phone_numbers)
    ]
