# Generated by Django 2.2.24 on 2022-04-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220413_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='fullname',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
